[workspace]
members = [
  "iroh",
  "iroh-bitswap",
  "iroh-car",
  "iroh-rpc",
  "iroh-rpc-client",
  "iroh-rpc-gateway",
  "iroh-rpc-network",
  "iroh-gateway",
  "iroh-metrics",
  "iroh-p2p",
  "iroh-store",
  "stores/*"
]
