[package]
name = "iroh-rpc-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroh-rpc = { path = "../iroh-rpc" }
serde = { version = "1.0", features = ["rc", "derive"] }
iroh-bitswap  = { path = "../iroh-bitswap" } 
libp2p = { version = "0.44.0", features = ["serde"] }
cid = { version = "0.8.0", features = ["serde-codec"] }
futures = "0.3.5"
