[package]
name = "iroh-rpc-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroh-rpc = { path = "../iroh-rpc" }
iroh-rpc-client = { path = "../iroh-rpc-client" }
libp2p = "0.44.0" 
cid = "0.8.4"
