[package]
name = "iroh-rpc-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iroh-rpc = { path = "../iroh-rpc" }
iroh-rpc-types = { path = "../iroh-rpc-types" }
iroh-rpc-client = { path = "../iroh-rpc-client" }
libp2p = "0.44.0" 
async-channel = "1.6.1"
futures = "0.3.21"
cid = "0.8.4"
tokio = { version = "1.17.0", features = ["full"] }
rkyv = { version = "0.7.37", features = ["std", "alloc", "validation"] }
bytes = "1.1.0"
